services:
  storage:
    container_name: storage
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: paper_trail
    volumes:
      - ./storage/db-init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

  storage-admin-ui:
    container_name: storage-admin-ui
    image: dpage/pgadmin4
    depends_on:
      - storage
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped