management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  info:
    env:
      enabled: true

# Everything above these dashes will be applied to all profiles
---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/paper_trail
    username: admin
    password: root
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect

infrastructure:
  endpoint: http://sqs.us-east-1.localhost.localstack.cloud:4566
  messaging:
    queue-url: ${infrastructure.endpoint}/000000000000/ACCOUNT_TRANSACTION_INGESTION_DATAFLOW

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://storage:5432/paper_trail
    username: admin
    password: root
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect

infrastructure:
  endpoint: http://infrastructure:4566
  messaging:
    queue-url: ${infrastructure.endpoint}/000000000000/ACCOUNT_TRANSACTION_INGESTION_DATAFLOW

---

spring:
  config:
    activate:
      on-profile: default
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://paper-trail-database.cluster-c2qboyuulbcj.us-east-1.rds.amazonaws.com
    username: postgresadmin
    password: changeit
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:otterandcow.com.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: otterandcow.com

infrastructure:
  endpoint: https://sqs.us-east-1.amazonaws.com
  messaging:
    queue-url: ${infrastructure.endpoint}/654918520080/ACCOUNT_TRANSACTION_INGESTION_DATAFLOW