management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  info:
    env:
      enabled: true

# Everything above these dashes will be applied to all profiles
---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/paper_trail
    username: admin
    password: root
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect

infrastructure:
  endpoint: http://sqs.us-east-1.localhost.localstack.cloud:4566
  messaging:
    queue-url: ${infrastructure.endpoint}/000000000000/ACCOUNT_TRANSACTION_INGESTION_DATAFLOW

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://storage:5432/paper_trail
    username: admin
    password: root
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect