openapi: "3.0.2"
info:
  title: Common API
  version: "1.0"
servers:
  - url: http://localhost/
paths: { }
components:
  schemas:
    ErrorResponse:
      type: object
      #      Commenting this since there is a constructor issue at compile time
      #      required:
      #        - message
      properties:
        messages:
          type: array
          items:
            type: string
            example: "Something went wrong"

