openapi: 3.0.0
info:
  title: Household REST API
  version: "1.0"
servers:
  - url: http://localhost/
paths:
  /household-members:
    get:
      operationId: getHouseholdMembers
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/HouseholdMember"
        204:
          description: No content
    post:
      operationId: createHouseholdMembers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              $ref: "#/components/schemas/HouseholdMember"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                $ref: "#/components/schemas/HouseholdMember"
        4XX:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/ErrorResponse"
        5XX:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/ErrorResponse"
components:
  schemas:
    HouseholdMember:
      type: object
      required:
        - householdId
        - userId
      properties:
        id:
          type: integer
        householdId:
          type: integer
          minimum: 1
        userId:
          type: integer
          minimum: 1
