openapi: 3.0.0
info:
  title: Users REST API
  version: "1.0"
servers:
  - url: http://localhost/
paths:
  /transactions:
    get:
      operationId: getTransactions
      parameters:
        - $ref: "#/components/parameters/AccountId"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Transaction"
        204:
          description: No content
    post:
      operationId: createTransactions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              $ref: "#/components/schemas/Transaction"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                $ref: "#/components/schemas/Transaction"
        4XX:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/ErrorResponse"
        5XX:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/ErrorResponse"
    put:
      operationId: updateTransaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Transaction"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transaction"
        4XX:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/ErrorResponse"
        5XX:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/ErrorResponse"
  /transactions/{transactionId}:
    parameters:
      - $ref: "#/components/parameters/TransactionId"
    delete:
      operationId: deleteTransaction
      responses:
        204:
          description: No content
        5XX:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/ErrorResponse"
    get:
      operationId: getTransaction
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transaction"
        204:
          description: No content
        4XX:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/ErrorResponse"
        5XX:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/ErrorResponse"
components:
  schemas:
    Transaction:
      type: object
      required:
        - accountId
        - amount
      properties:
        id:
          type: integer
        accountId:
          type: integer
          minimum: 1
        amount:
          type: integer
          description: Amount in pennies
          minLength: 1
        description:
          type: string
          minLength: 1
  parameters:
    AccountId:
      in: query
      name: accountId
      required: false
      schema:
        type: integer
    TransactionId:
      in: path
      name: transactionId
      required: true
      schema:
        type: integer

