name: Docker Testing
on:
  push:
    branches:
      - feature/GHA-docker-int-testing

jobs:
  Pull-Request:
    name: Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "corretto"
          cache: "maven"

      - name: Check Maven version
        run: mvn --version

      - name: Check Docker version
        run: docker --version

      #      - name: Build Application
      #        run: mvn clean install --no-transfer-progress --batch-mode

      - name: Build Application with Docker
        run: mvn clean install --activate-profiles docker --no-transfer-progress --batch-mode